### ISSUE TITLE
Nodes außerhalb des Hintergrundbilds

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/fieldmon#10]
Beim Testen mit weniger Steinen auf Prod ist mir aufgefallen, dass mache Nodes initial außerhalb des sichtbaren Bereiches erscheinen - sie sind verdeckt. Das ist grundsätzlich nicht schlimm, da die Zoomstufe heranzoomen auf einem Bereich erlaubt. Es ist aber unerwartet, wenn das Hintergrund-Bild vollständig sichtbar ist.

Falls ein Hintergrundbild gesetzt ist, sollten alle nicht-fixierten Nodes auch darauf platziert werden.

**Comment by yanosz** [comment]
@Rixxc Hättest Du Lust und Zeit danach zu sehen? Soweit ich weiß, war der Initial-Code von Dir.

**Comment by Rixxc** [comment]
Kan ich gerne übernehmen. Ich werde aber vermutlich frühstens am Freitag nächster Woche dazu kommen

**Comment by yanosz** [comment]
Danke - kein Stress. Wenn's diesen Monat passt, wär's mehr als ausreichend :)

**Comment by Rixxc** [comment]
Das Issue sollte mit commit 1ce167c1d9c9e3c74eaeb8478a4747377e59c7c1 gelöst sein.
Ich habe eine initiale Transformation des Koordinatensystems auf die Mitte des Canvas vorgenommen.
